#!/usr/bin/env node

const { Command } = require('commander');
const program = new Command();

program
	.description('Generate Frigg API Modules')
	.option('-m, --module <name>', 'Add an API Module', 'ExampleApi')
	.option('-a, --auth <type>', 'Add an Authentication Strategy', 'OAuth2');

program.parse();

const options = program.opts();
console.log('API module generated.');
